version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
    - location: scripts/start
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop
      timeout: 300
      runas: root